allowBuilds:
  core-js: true
  core-js-pure: true
  ejs: true
  esbuild: true
  fsevents: true
  highlight.js: true
  styled-components: true
disallowWorkspaceCycles: true

minimumReleaseAge: 4320
patchedDependencies:
  csstype@3.2.3: patches/csstype@3.2.3.patch
