SUB rela
blanko.ppp = keisix(2, INT(100 * RND) + 1)
blanko.age = keisix(3, INT(100 * RND) + 1)
blanko.ego = keisix(4, INT(100 * RND) + 1)
blanko.ldr = keisix(5, INT(100 * RND * RND) + 1)
blanko.kar = keisix(6, INT(100 * RND * RND) + 1)
blanko.yvo = keisix(7, INT(100 * RND) + 1)
blanko.avo = keisix(7, INT(100 * RND) + 1)
mahmax
blanko.nam = krj$ + "." + ptemp$
blanko.nat = nats
END SUB

