// AUTO-GENERATED by src/data/mhm2000/generate-calendar.ts on first
// pass, then HAND-EDITED. After generation this file is the source of
// truth for the runtime calendar — tweak it directly. Re-run the
// generator only if the raw KIERO.M2K decode itself changes
// (`src/data/mhm2000/calendar.ts`), and expect to redo any manual
// tweaks afterwards.
//
// The runtime engine (gameMachine) reads `calendar` exclusively. The
// raw decode in `./mhm2000/calendar.ts` is kept around as
// cross-reference, not as a runtime dependency.

import type { CompetitionId } from "@/types/competitions";
import type { SeasonAction } from "@/state/game";

export type Seed = {
  competition: CompetitionId;
  phase: number;
};

export type CalendarEntry = {
  round: number;
  title?: string;
  phases: string[];
  gamedays: CompetitionId[];
  seed: Seed[];
  transferMarket: boolean;
  crisisMeeting: boolean;
  createRandomEvent: boolean;
  pranks: boolean;
  tags: string[];
  requiredActions?: SeasonAction[];
};

type RawCalendarEntry = Omit<CalendarEntry, "round">;

const entries: RawCalendarEntry[] = [
  {
    phases: ["start_of_season", "seed"],
    seed: [
      { competition: "phl", phase: 0 },
      { competition: "division", phase: 0 },
      { competition: "mutasarja", phase: 0 },
      { competition: "ehl", phase: 0 },
      { competition: "practice", phase: 0 },
      { competition: "cup", phase: 0 }
    ],
    gamedays: [],
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    transferMarket: true,
    tags: []
  },

  // round 0 (KIERO.M2K row 1, type 99) — preseason: transfer market opens, mass börsi generation + cup draw
  {
    title: "Esikausi",
    phases: ["action", "prank", "event_creation", "event", "news", "seed"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["preseason", "preRound:bors-init", "todo:wire-bors-mass-gen"],
    requiredActions: ["budget"]
  },
  // round 1 (KIERO.M2K row 2, type 99) — preseason: sponsorit (sponsor draw)
  {
    title: "Esikausi",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["preseason", "preRound:sponsorit", "todo:wire-sponsorit"]
  },
  // round 2 (KIERO.M2K row 3, type 99) — preseason filler
  {
    title: "Esikausi",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["preseason"]
  },
  // round 3 (KIERO.M2K row 4, type 99) — preseason filler
  {
    title: "Esikausi",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["preseason"]
  },
  // round 4 (KIERO.M2K row 5, type 99) — preseason filler
  {
    title: "Esikausi",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["preseason"]
  },
  // round 5 (KIERO.M2K row 6, type 99) — preseason filler
  {
    title: "Esikausi",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["preseason"],
    requiredActions: ["strategy"]
  },
  // round 6 (KIERO.M2K row 7, type 4) — training match
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["practice"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["preseason", "training", "todo:wire-practice-competition"]
  },
  // round 7 (KIERO.M2K row 8, type 4) — training match: valitsestrat (strategy selection)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["practice"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["preseason", "training", "preRound:strategy-selection"]
  },
  // round 8 (KIERO.M2K row 9, type 4) — training match: tremaar (tactics refresh)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["practice"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["preseason", "training", "preRound:tactics"]
  },
  // round 9 (KIERO.M2K row 10, type 4) — training match: zreseasongala (season-opening gala)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["practice"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    requiredActions: ["championshipBet", "sponsor"],
    tags: [
      "preseason",
      "training",
      "preRound:season-opening-gala",
      "todo:wire-opening-gala"
    ]
  },
  // round 10 (KIERO.M2K row 11, type 1) — regular gameday 1
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 11 (KIERO.M2K row 12, type 1) — regular gameday 2
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 12 (KIERO.M2K row 13, type 3) — cup gameday
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["todo:wire-cup-competition"]
  },
  // round 13 (KIERO.M2K row 14, type 1) — regular gameday 3
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 14 (KIERO.M2K row 15, type 3) — cup gameday (phase 0 leg 2) + cuparpo (R32 draw)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [{ competition: "cup", phase: 1 }],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["cup-draw"]
  },
  // round 15 (KIERO.M2K row 16, type 2) — EHL gameday
  {
    phases: ["action", "gameday", "event", "news"],
    gamedays: ["ehl"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 16 (KIERO.M2K row 17, type 96) — vapaa viikonloppu (free weekend)
  {
    title: "Vapaa viikonloppu",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["free-weekend"]
  },
  // round 17 (KIERO.M2K row 18, type 1) — regular gameday 4
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 18 (KIERO.M2K row 19, type 1) — regular gameday 5
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 19 (KIERO.M2K row 20, type 2) — EHL gameday
  {
    phases: ["action", "gameday", "event", "news"],
    gamedays: ["ehl"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 20 (KIERO.M2K row 21, type 1) — regular gameday 6 + UNKNOWN kiero3=3
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick", "unknown:preRound=3"]
  },
  // round 21 (KIERO.M2K row 22, type 1) — regular gameday 7 + UNKNOWN kiero3=3
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick", "unknown:preRound=3"]
  },
  // round 22 (KIERO.M2K row 23, type 1) — regular gameday 8 + UNKNOWN kiero3=3
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick", "unknown:preRound=3"]
  },
  // round 23 (KIERO.M2K row 24, type 2) — EHL gameday + tarkistanhlc (NHL champion check)
  {
    phases: ["action", "gameday", "event", "news"],
    gamedays: ["ehl"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["preRound:nhl-champion-check", "todo:wire-nhl-champion-check"]
  },
  // round 24 (KIERO.M2K row 25, type 1) — regular gameday 9
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 25 (KIERO.M2K row 26, type 97) — maajoukkuetauko (national team break)
  {
    title: "Maajoukkuetauko",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["national-team-break"]
  },
  // round 26 (KIERO.M2K row 27, type 1) — regular gameday 10
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 27 (KIERO.M2K row 28, type 3) — cup gameday
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 28 (KIERO.M2K row 29, type 1) — regular gameday 11
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 29 (KIERO.M2K row 30, type 3) — cup gameday (phase 1 leg 2) + cuparpo (R16 draw)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [{ competition: "cup", phase: 2 }],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["cup-draw"]
  },
  // round 30 (KIERO.M2K row 31, type 2) — EHL gameday
  {
    phases: ["action", "gameday", "event", "news"],
    gamedays: ["ehl"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 31 (KIERO.M2K row 32, type 1) — regular gameday 12
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 32 (KIERO.M2K row 33, type 1) — regular gameday 13
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 33 (KIERO.M2K row 34, type 1) — regular gameday 14
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 34 (KIERO.M2K row 35, type 2) — EHL gameday
  {
    phases: ["action", "gameday", "event", "news"],
    gamedays: ["ehl"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 35 (KIERO.M2K row 36, type 1) — regular gameday 15
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 36 (KIERO.M2K row 37, type 96) — vapaa viikonloppu
  {
    title: "Vapaa viikonloppu",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["free-weekend"]
  },
  // round 37 (KIERO.M2K row 38, type 1) — regular gameday 16
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 38 (KIERO.M2K row 39, type 1) — regular gameday 17
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 39 (KIERO.M2K row 40, type 2) — EHL gameday
  {
    phases: ["action", "gameday", "event", "news", "seed"],
    gamedays: ["ehl"],
    seed: [{ competition: "ehl", phase: 1 }],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 40 (KIERO.M2K row 41, type 1) — regular gameday 18
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 41 (KIERO.M2K row 42, type 1) — regular gameday 19
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 42 (KIERO.M2K row 43, type 1) — regular gameday 20
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [{ competition: "tournaments", phase: 0 }],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 43 (KIERO.M2K row 44, type 1) — regular gameday 21
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 44 (KIERO.M2K row 45, type 3) — cup gameday
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 45 (KIERO.M2K row 46, type 1) — regular gameday 22
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 46 (KIERO.M2K row 47, type 98) — kutsuturnaus (Christmas invitation tournaments window)
  {
    title: "Kutsuturnaukset",
    seed: [],
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["tournaments"],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["invitation-tournaments", "christmas"]
  },
  // round 47 (KIERO.M2K row 48, type 97) — maajoukkuetauko
  {
    title: "Maajoukkuetauko",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["national-team-break"]
  },
  // round 48 (KIERO.M2K row 49, type 1) — regular gameday 23 + suunnitelma (budget / planning)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick", "preRound:budget", "todo:wire-budget"]
  },
  // round 49 (KIERO.M2K row 50, type 3) — cup gameday (phase 2 leg 2) + cuparpo (QF draw)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [{ competition: "cup", phase: 3 }],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["cup-draw"]
  },
  // round 50 (KIERO.M2K row 51, type 1) — regular gameday 24
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 51 (KIERO.M2K row 52, type 1) — regular gameday 25
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 52 (KIERO.M2K row 53, type 1) — regular gameday 26 + mmkisaalku (WCh starts)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: [
      "readiness-tick",
      "preRound:wch-start",
      "todo:wire-world-championships"
    ]
  },
  // round 53 (KIERO.M2K row 54, type 1) — regular gameday 27
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 54 (KIERO.M2K row 55, type 1) — regular gameday 28
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 55 (KIERO.M2K row 56, type 22) — EHL final tournament + mmkisaloppu (WCh ends)
  {
    title: "EHL:n lopputurnaus",
    phases: ["action", "gameday", "event", "news"],
    gamedays: ["ehl"],
    seed: [{ competition: "ehl", phase: 1 }],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["ehl-final-tournament", "preRound:wch-end"]
  },
  // round 56 (KIERO.M2K row 57, type 1) — regular gameday 29 — last round with market open
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: true,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick", "last-round-with-market-open"]
  },
  // round 57 (KIERO.M2K row 58, type 1) — regular gameday 30 — market just closed
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick", "market-closes-here"]
  },
  // round 58 (KIERO.M2K row 59, type 3) — cup gameday
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 59 (KIERO.M2K row 60, type 1) — regular gameday 31
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 60 (KIERO.M2K row 61, type 3) — cup gameday (phase 3 leg 2) + cuparpo (SF draw)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [{ competition: "cup", phase: 4 }],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["cup-draw"]
  },
  // round 61 (KIERO.M2K row 62, type 1) — regular gameday 32
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 62 (KIERO.M2K row 63, type 1) — regular gameday 33
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 63 (KIERO.M2K row 64, type 97) — maajoukkuetauko
  {
    title: "Maajoukkuetauko",
    phases: ["action", "prank", "event_creation", "event", "news"],
    gamedays: [],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["national-team-break"]
  },
  // round 64 (KIERO.M2K row 65, type 1) — regular gameday 34
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 65 (KIERO.M2K row 66, type 1) — regular gameday 35
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 66 (KIERO.M2K row 67, type 1) — regular gameday 36
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 67 (KIERO.M2K row 68, type 1) — regular gameday 37
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 68 (KIERO.M2K row 69, type 1) — regular gameday 38
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 69 (KIERO.M2K row 70, type 1) — regular gameday 39
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 70 (KIERO.M2K row 71, type 3) — cup gameday
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: []
  },
  // round 71 (KIERO.M2K row 72, type 1) — regular gameday 40
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 72 (KIERO.M2K row 73, type 3) — cup gameday (phase 4 leg 2) + cuparpo (Final draw)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [{ competition: "cup", phase: 5 }],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["cup-draw"]
  },
  // round 73 (KIERO.M2K row 74, type 1) — regular gameday 41
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 74 (KIERO.M2K row 75, type 1) — regular gameday 42
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 75 (KIERO.M2K row 76, type 1) — regular gameday 43
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick"]
  },
  // round 76 (KIERO.M2K row 77, type 1) — regular gameday 44 — last regular gameday
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["readiness-tick", "last-regular-gameday"]
  },
  // round 77 (KIERO.M2K row 78, type 41) — QF draw
  {
    title: "Puolivälieräpläjäys",
    phases: ["action", "prank", "event_creation", "event", "news", "seed"],
    gamedays: [],
    seed: [
      { competition: "phl", phase: 1 },
      { competition: "division", phase: 1 },
      { competition: "mutasarja", phase: 1 }
    ],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["playoffs", "playoff-draw"]
  },
  // round 78 (KIERO.M2K row 79, type 42) — QF game 1
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 79 (KIERO.M2K row 80, type 42) — QF game 2
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 80 (KIERO.M2K row 81, type 42) — QF game 3
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 81 (KIERO.M2K row 82, type 42) — QF game 4
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 82 (KIERO.M2K row 83, type 42) — QF game 5
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 83 (KIERO.M2K row 84, type 43) — SF draw
  {
    title: "Välieräpläjäys",
    phases: ["action", "prank", "event_creation", "event", "news", "seed"],
    gamedays: [],
    seed: [
      { competition: "phl", phase: 2 },
      { competition: "division", phase: 2 },
      { competition: "mutasarja", phase: 2 }
    ],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["playoffs", "playoff-draw"]
  },
  // round 84 (KIERO.M2K row 85, type 44) — SF game 1
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 85 (KIERO.M2K row 86, type 44) — SF game 2
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 86 (KIERO.M2K row 87, type 44) — SF game 3
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 87 (KIERO.M2K row 88, type 44) — SF game 4
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 88 (KIERO.M2K row 89, type 44) — SF game 5
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 89 (KIERO.M2K row 90, type 45) — Final draw
  {
    title: "Finaalipläjäys",
    phases: ["action", "prank", "event_creation", "event", "news", "seed"],
    gamedays: [],
    seed: [
      { competition: "phl", phase: 3 },
      { competition: "division", phase: 3 },
      { competition: "mutasarja", phase: 3 }
    ],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["playoffs", "playoff-draw"]
  },
  // round 90 (KIERO.M2K row 91, type 46) — Final game 1
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 91 (KIERO.M2K row 92, type 46) — Final game 2
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 92 (KIERO.M2K row 93, type 46) — Final game 3
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 93 (KIERO.M2K row 94, type 46) — Final game 4
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 94 (KIERO.M2K row 95, type 46) — Final game 5
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["phl", "division", "mutasarja"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["playoffs"]
  },
  // round 95 (KIERO.M2K row 96, type 3) — PA Cup final, leg 1
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["cup-final-leg-1"]
  },
  // round 96 (KIERO.M2K row 97, type 3) — PA Cup final, leg 2 + cupjuhla (trophy ceremony)
  {
    phases: [
      "action",
      "prank",
      "gameday",
      "calculations",
      "event_creation",
      "event",
      "news",
      "seed"
    ],
    gamedays: ["cup"],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: true,
    pranks: true,
    tags: ["cup-final-leg-2", "cup-celebration"]
  },
  // round 97 (KIERO.M2K row 98, type 47) — PHL juhlagaala (season-end gala)
  {
    title: "PHL:n juhlagaala",
    phases: ["action", "event", "news", "gala"],
    gamedays: [],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["season-end-gala"]
  },
  // round 98 (KIERO.M2K row 99, type 48) — uusikausi (rollover marker)
  {
    title: "Uusi kausi",
    phases: ["action", "end_of_season"],
    gamedays: [],
    seed: [],
    transferMarket: false,
    crisisMeeting: true,
    createRandomEvent: false,
    pranks: false,
    tags: ["season-rollover"]
  }
];

const calendar = entries.map((entry, round) => {
  return {
    round,
    ...entry
  };
});

export default calendar;
